<?php

return
	[
		[
			'id'          => 'hpmor1',
			'title'       => 'Harry Potter and the Methods of Rationality: Book 1',
			'title_short' => 'HPMoR: Book 1',
			'date'        => '2015-04-04',
			'repository'  => 'https://github.com/Mikescher/HPMOR-LyX',
			'pages'       => '597',
			'pdf'         => 'https://github.com/Mikescher/HPMOR-LyX/raw/master/hpmor_volume1_16x23.pdf',
			'online'      => 'http://www.hpmor.com/',
			'author'      => 'Eliezer Yudkowsky',
			'size'        => [17.0, 24.0],
			'imagecount'  => 4,
		],

		[
			'id'          => 'hpmor2',
			'title'       => 'Harry Potter and the Methods of Rationality: Book 2',
			'title_short' => 'HPMoR: Book 2',
			'date'        => '2015-04-04',
			'repository'  => 'https://github.com/Mikescher/HPMOR-LyX',
			'pages'       => '719',
			'pdf'         => 'https://github.com/Mikescher/HPMOR-LyX/raw/master/hpmor_volume2_16x23.pdf',
			'online'      => 'http://www.hpmor.com/',
			'author'      => 'Eliezer Yudkowsky',
			'size'        => [17.0, 24.0],
			'imagecount'  => 4,
		],

		[
			'id'          => 'hpmor3',
			'title'       => 'Harry Potter and the Methods of Rationality: Book 3',
			'title_short' => 'HPMoR: Book 3',
			'date'        => '2015-04-04',
			'repository'  => 'https://github.com/Mikescher/HPMOR-LyX',
			'pages'       => '493',
			'pdf'         => 'https://github.com/Mikescher/HPMOR-LyX/raw/master/hpmor_volume3_16x23.pdf',
			'online'      => 'http://www.hpmor.com/',
			'author'      => 'Eliezer Yudkowsky',
			'size'        => [17.0, 24.0],
			'imagecount'  => 4,
		],

		[
			'id'          => 'apgte1',
			'title'       => 'A Practical Guide to Evil: Book 1',
			'title_short' => 'APGtE: Book 1',
			'date'        => '2016-12-23',
			'repository'  => 'https://gitlab.com/Mikescher2/A-Practical-Guide-To-Evil-Lyx',
			'pages'       => '501',
			'pdf'         => [],
			'online'      => 'https://practicalguidetoevil.wordpress.com/',
			'author'      => 'David Verburg',
			'size'        => [12.5, 19.0],
			'imagecount'  => 4,
		],

		[
			'id'          => 'mm',
			'title'       => 'The Metropolitan Man',
			'title_short' => 'The Metropolitan Man',
			'date'        => '2017-12-02',
			'repository'  => 'https://github.com/Mikescher/Metropolitan-Man-Lyx',
			'pages'       => '258',
			'pdf'         => 'https://github.com/Mikescher/Metropolitan-Man-Lyx/raw/master/src/MM.pdf',
			'online'      => 'https://www.fanfiction.net/s/10360716/1/',
			'author'      => 'Alexandr Wales',
			'size'        => [12.5, 19.0],
			'imagecount'  => 4,
		],

		[
			'id'          => 'mol',
			'title'       => 'Mother of Learning',
			'title_short' => 'Mother of Learning',
			'date'        => '2019-11-24',
			'repository'  => 'https://github.com/Mikescher/Mother-of-Learning-Lyx',
			'pages'       => ['298', '328', '330', '362', '372', '346', '396', '272'],
			'pdf'         =>
			[
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_1_1.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_1_2.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_2_1.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_2_2.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_3_1.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_3_2.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_3_3.pdf',
				'https://github.com/Mikescher/Mother-of-Learning-Lyx/blob/master/build/Book_3_4.pdf',
			],
			'online'      => 'https://www.fictionpress.com/s/2961893',
			'author'      => 'Domagoj Kurmaic',
			'size'        => [12.5, 19.0],
			'imagecount'  => 5,
		],
	];
