<?php

return
	[
		'2017' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'Inverse Captcha',                         'language' => 'pyth', 'solutions' => ['1390', '1232'] ],
			['day' =>  2, 'parts' => 2, 'title' => 'Corruption Checksum',                     'language' => 'pyth', 'solutions' => ['32020', '236'] ],
			['day' =>  3, 'parts' => 2, 'title' => 'Spiral Memory',                           'language' => 'pyth', 'solutions' => ['419', '295229'] ],
			['day' =>  4, 'parts' => 2, 'title' => 'High-Entropy Passphrases',                'language' => 'pyth', 'solutions' => ['477', '167'] ],
			['day' =>  5, 'parts' => 2, 'title' => 'A Maze of Twisty Trampolines, All Alike', 'language' => 'pyth', 'solutions' => ['388611', '27763113'] ],
			['day' =>  6, 'parts' => 2, 'title' => 'Memory Reallocation',                     'language' => 'pyth', 'solutions' => ['11137', '1037'] ],
			['day' =>  7, 'parts' => 2, 'title' => 'Recursive Circus',                        'language' => 'pyth', 'solutions' => ['hlqnsbe', '1993'] ],
			['day' =>  8, 'parts' => 2, 'title' => 'I Heard You Like Registers',              'language' => 'pyth', 'solutions' => ['6343', '7184'] ],
			['day' =>  9, 'parts' => 2, 'title' => 'Stream Processing',                       'language' => 'pyth', 'solutions' => ['7640', '4368'] ],
			['day' => 10, 'parts' => 2, 'title' => 'Knot Hash',                               'language' => 'pyth', 'solutions' => ['2928', '0c2f794b2eb555f7830766bf8fb65a16'] ],
		],
		'2018' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'Chronal Calibration',                     'language' => 'cs', 'solutions' => ['490', '70357'] ],
			['day' =>  2, 'parts' => 2, 'title' => 'Inventory Management System',             'language' => 'cs', 'solutions' => ['5434', 'agimdjvlhedpsyoqfzuknpjwt'] ],
			['day' =>  3, 'parts' => 2, 'title' => 'No Matter How You Slice It',              'language' => 'cs', 'solutions' => ['116489', '1260'] ],
			['day' =>  4, 'parts' => 2, 'title' => 'Repose Record',                           'language' => 'cs', 'solutions' => ['143415', '49944'] ],
			['day' =>  5, 'parts' => 2, 'title' => 'Alchemical Reduction',                    'language' => 'cs', 'solutions' => ['10368', '4122'] ],
			['day' =>  6, 'parts' => 2, 'title' => 'Chronal Coordinates',                     'language' => 'cs', 'solutions' => ['2917', '44202'] ],
			['day' =>  7, 'parts' => 2, 'title' => 'The Sum of Its Parts',                    'language' => 'cs', 'solutions' => ['GKPTSLUXBIJMNCADFOVHEWYQRZ', '920'] ],
			['day' =>  8, 'parts' => 2, 'title' => 'Memory Maneuver',                         'language' => 'cs', 'solutions' => ['45194', '22989'] ],
			['day' =>  9, 'parts' => 2, 'title' => 'Marble Mania',                            'language' => 'cs', 'solutions' => ['398242', '3273842452'] ],
			['day' => 10, 'parts' => 2, 'title' => 'The Stars Align',                         'language' => 'cs', 'solutions' => ['KFLBHXGK', '10659'] ],
			['day' => 11, 'parts' => 2, 'title' => 'Chronal Charge',                          'language' => 'cs', 'solutions' => ['34,13', '280,218,11'] ],
			['day' => 12, 'parts' => 2, 'title' => 'Subterranean Sustainability',             'language' => 'cs', 'solutions' => ['3738', '3900000002467'] ],
			['day' => 13, 'parts' => 2, 'title' => 'Mine Cart Madness',                       'language' => 'cs', 'solutions' => ['124,90', '145,88'] ],
			['day' => 14, 'parts' => 2, 'title' => 'Chocolate Charts',                        'language' => 'cs', 'solutions' => ['9276422810', '20319117'] ],
			['day' => 15, 'parts' => 2, 'title' => 'Beverage Bandits',                        'language' => 'cs', 'solutions' => ['201123', '54188'] ],
			['day' => 16, 'parts' => 2, 'title' => 'Chronal Classification',                  'language' => 'cs', 'solutions' => ['592', '557'] ],
			['day' => 17, 'parts' => 2, 'title' => 'Reservoir Research',                      'language' => 'cs', 'solutions' => ['33004', '23294'] ],
			['day' => 18, 'parts' => 2, 'title' => 'Settlers of The North Pole',              'language' => 'cs', 'solutions' => ['536370', '190512'] ],
			['day' => 19, 'parts' => 2, 'title' => 'Go With The Flow',                        'language' => 'cs', 'solutions' => ['1440', '15827040'] ],
			['day' => 20, 'parts' => 2, 'title' => 'A Regular Map',                           'language' => 'cs', 'solutions' => ['3675', '7953'] ],
			['day' => 21, 'parts' => 2, 'title' => 'Chronal Conversion',                      'language' => 'cs', 'solutions' => ['103548', '14256686'] ],
			['day' => 22, 'parts' => 2, 'title' => 'Mode Maze',                               'language' => 'cs', 'solutions' => ['11972', '1092'] ],
			['day' => 23, 'parts' => 2, 'title' => 'Experimental Emergency Teleportation',    'language' => 'cs', 'solutions' => ['417', '112997634'] ],
			['day' => 24, 'parts' => 2, 'title' => 'Immune System Simulator 20XX',            'language' => 'cs', 'solutions' => ['21070', '7500'] ],
			['day' => 25, 'parts' => 1, 'title' => 'Four-Dimensional Adventure',              'language' => 'cs', 'solutions' => ['407'] ],
		],
		'2019' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'The Tyranny of the Rocket Equation',      'language' => 'ts', 'solutions' => ['3464458', '5193796'] ],
			['day' =>  2, 'parts' => 2, 'title' => '1202 Program Alarm',                      'language' => 'ts', 'solutions' => ['3267740', '7870'] ],
			['day' =>  3, 'parts' => 2, 'title' => 'Crossed Wires',                           'language' => 'ts', 'solutions' => ['399', '15678'] ],
			['day' =>  4, 'parts' => 2, 'title' => 'Secure Container',                        'language' => 'ts', 'solutions' => ['979', '635'] ],
			['day' =>  5, 'parts' => 2, 'title' => 'Sunny with a Chance of Asteroids',        'language' => 'ts', 'solutions' => ['8332629', '8805067'] ],
			['day' =>  6, 'parts' => 2, 'title' => 'Universal Orbit Map',                     'language' => 'ts', 'solutions' => ['333679', '370'] ],
			['day' =>  7, 'parts' => 2, 'title' => 'Amplification Circuit',                   'language' => 'ts', 'solutions' => ['844468', '4215746'] ],
			['day' =>  8, 'parts' => 2, 'title' => 'Space Image Format',                      'language' => 'ts', 'solutions' => ['2286', 'CJZLP'] ],
			['day' =>  9, 'parts' => 2, 'title' => 'Sensor Boost',                            'language' => 'ts', 'solutions' => ['2738720997', '50894'] ],
			['day' => 10, 'parts' => 2, 'title' => 'Monitoring Station',                      'language' => 'ts', 'solutions' => ['344', '2732'] ],
			['day' => 11, 'parts' => 2, 'title' => 'Space Police',                            'language' => 'ts', 'solutions' => ['2021', 'LBJHEKLH'] ],
			['day' => 12, 'parts' => 2, 'title' => 'The N-Body Problem',                      'language' => 'ts', 'solutions' => ['9999', '282399002133976'] ],
			['day' => 13, 'parts' => 2, 'title' => 'Care Package',                            'language' => 'ts', 'solutions' => ['326', '15988'] ],
			['day' => 14, 'parts' => 2, 'title' => 'Space Stoichiometry',                     'language' => 'ts', 'solutions' => ['168046', '6972986'] ],
			['day' => 15, 'parts' => 2, 'title' => 'Oxygen System',                           'language' => 'ts', 'solutions' => ['244', '278'] ],
            ['day' => 16, 'parts' => 2, 'title' => 'Flawed Frequency Transmission',           'language' => 'ts', 'solutions' => ['69549155', '83253465'] ],
            ['day' => 17, 'parts' => 2, 'title' => 'Set and Forget',                          'language' => 'ts', 'solutions' => ['3448', '762405'] ],
            ['day' => 18, 'parts' => 2, 'title' => 'Many-Worlds Interpretation',              'language' => 'ts', 'solutions' => ['7430', '1864'] ],
            ['day' => 19, 'parts' => 2, 'title' => 'Tractor Beam',                            'language' => 'ts', 'solutions' => ['181', '4240964'] ],
            ['day' => 20, 'parts' => 2, 'title' => 'Donut Maze',                              'language' => 'ts', 'solutions' => ['602', '6986'] ],
            ['day' => 21, 'parts' => 2, 'title' => 'Springdroid Adventure',                   'language' => 'ts', 'solutions' => ['19361023', '1141457530'] ],
            ['day' => 22, 'parts' => 2, 'title' => 'Slam Shuffle',                            'language' => 'ts', 'solutions' => ['1252', '46116012647793'] ],
            ['day' => 23, 'parts' => 2, 'title' => 'Category Six',                            'language' => 'ts', 'solutions' => ['27061', '19406'] ],
			['day' => 24, 'parts' => 2, 'title' => 'Planet of Discord',                       'language' => 'ts', 'solutions' => ['25719471', '1916'] ],
			['day' => 25, 'parts' => 1, 'title' => 'Cryostasis',                              'language' => 'ts', 'solutions' => ['2236672'] ],
		],
		'2020' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'Report Repair',                           'language' => 'rust', 'solutions' => ['1009899', '44211152'] ],
			['day' =>  2, 'parts' => 2, 'title' => 'Password Philosophy',                     'language' => 'rust', 'solutions' => ['564', '325'] ],
			['day' =>  3, 'parts' => 2, 'title' => 'Toboggan Trajectory',                     'language' => 'rust', 'solutions' => ['181', '1260601650'] ],
			['day' =>  4, 'parts' => 2, 'title' => 'Passport Processing',                     'language' => 'rust', 'solutions' => ['222', '140'] ],
			['day' =>  5, 'parts' => 2, 'title' => 'Binary Boarding',                         'language' => 'rust', 'solutions' => ['842', '617'] ],
			['day' =>  6, 'parts' => 2, 'title' => 'Custom Customs',                          'language' => 'rust', 'solutions' => ['6683', '3122'] ],
			['day' =>  7, 'parts' => 2, 'title' => 'Handy Haversacks',                        'language' => 'rust', 'solutions' => ['296', '9339'] ],
			['day' =>  8, 'parts' => 2, 'title' => 'Handheld Halting',                        'language' => 'rust', 'solutions' => ['1684', '2188'] ],
			['day' =>  9, 'parts' => 2, 'title' => 'Encoding Error',                          'language' => 'rust', 'solutions' => ['69316178', '9351526'] ],
			['day' => 10, 'parts' => 2, 'title' => 'Adapter Array',                           'language' => 'rust', 'solutions' => ['1904', '10578455953408'] ],
			['day' => 11, 'parts' => 2, 'title' => 'Seating System',                          'language' => 'rust', 'solutions' => ['2321', '2102'] ],
			['day' => 12, 'parts' => 2, 'title' => 'Rain Risk',                               'language' => 'rust', 'solutions' => ['2270', '138669'] ],
			['day' => 13, 'parts' => 2, 'title' => 'Shuttle Search',                          'language' => 'rust', 'solutions' => ['1915', '294354277694107'] ],
			['day' => 14, 'parts' => 2, 'title' => 'Docking Data',                            'language' => 'rust', 'solutions' => ['12408060320841', '4466434626828'] ],
			['day' => 15, 'parts' => 2, 'title' => 'Rambunctious Recitation',                 'language' => 'rust', 'solutions' => ['273', '47205'] ],
		    ['day' => 16, 'parts' => 2, 'title' => 'Ticket Translation',                      'language' => 'rust', 'solutions' => ['29019', '517827547723'] ],
			['day' => 17, 'parts' => 2, 'title' => 'Conway Cubes',                            'language' => 'rust', 'solutions' => ['276', '2136'] ],
			['day' => 18, 'parts' => 2, 'title' => 'Operation Order',                         'language' => 'rust', 'solutions' => ['75592527415659', '360029542265462'] ],
			['day' => 19, 'parts' => 2, 'title' => 'Monster Messages',                        'language' => 'rust', 'solutions' => ['142', '294'] ],
			['day' => 20, 'parts' => 2, 'title' => 'Jurassic Jigsaw',                         'language' => 'rust', 'solutions' => ['64802175715999', '2146'] ],
			['day' => 21, 'parts' => 2, 'title' => 'Allergen Assessment',                     'language' => 'rust', 'solutions' => ['1913', 'gpgrb,tjlz,gtjmd,spbxz,pfdkkzp,xcfpc,txzv,znqbr'] ],
			['day' => 22, 'parts' => 2, 'title' => 'Crab Combat',                             'language' => 'rust', 'solutions' => ['32495', '32665'] ],
			['day' => 23, 'parts' => 2, 'title' => 'Crab Cups',                               'language' => 'rust', 'solutions' => ['27865934', '170836011000'] ],
		  	['day' => 24, 'parts' => 2, 'title' => 'Lobby Layout',                            'language' => 'rust', 'solutions' => ['459', '4150'] ],
		  	['day' => 25, 'parts' => 1, 'title' => 'Combo Breaker',                           'language' => 'rust', 'solutions' => ['3217885'] ],
		],
		'2021' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'Sonar Sweep',                             'language' => 'go',   'solutions' => ['1715', '1739'] ],
			['day' =>  2, 'parts' => 2, 'title' => 'Dive!',                                   'language' => 'go',   'solutions' => ['1451208', '1620141160'] ],
			['day' =>  3, 'parts' => 2, 'title' => 'Binary Diagnostic',                       'language' => 'go',   'solutions' => ['2954600', '1662846'] ],
		],
		'2022' =>
		[
			['day' =>  1, 'parts' => 2, 'title' => 'Calorie Counting',                        'language' => 'nim',  'solutions' => ['66719', '198551'] ],
		]
	];
